### PR TITLE
installationsPercentage is singular in older reports. Fixes broken plugin-site-api generation

### PR DESCRIPTION
**Pull request by halkeye**
see https://ci.jenkins.io/job/Infra/job/plugin-site-api/job/master/341/consoleFull

### CODE REVIEW

**Review by abayer — APPROVED** [review]

**Comment by abayer** [comment]
Thanks! I was sure I'd miss _something_. =)

**Comment by abayer** [comment]
I'll push the updated stats.jenkins.io in ~30 minutes.

**Comment by halkeye** [comment]
btw by deleting gh-pages branch you will break a bunch of stuff on next run

**Comment by abayer** [comment]
Not sure what you mean with "deleting gh-pages branch" - I'll just be updating the branch in infra-statistics.

**Comment by abayer** [comment]
In any case, pushed to infra-statistics. =)

**Comment by halkeye** [comment]
Well the branch is gone right now (see https://github.com/jenkins-infra/jenkins-usage-stats/branches/all)
I know both plugin-site and plugin-site-api checkout that branch
I'm doing plugin-site-api work right now, so I'll make sure to not restart the dev process

edit: scratch that, plugin-site uses https://stats.jenkins.io/jenkins-stats/svg/total-jenkins.csv but API uses the branch

**Comment by abayer** [comment]
Aaaah, the api should keep using the branch in infra-statistics for the time being - as of now, this repo is just being used to generate the reports, and then I manually push to gh-pages in infra-statistics.git. That may change in the future, but not for now.

**Comment by halkeye** [comment]
🤦 my bad, i didn't realize we were in the different repo, too many open tabs too much fire fighting. Its using usage statistics

**Comment by abayer** [comment]
No worries, and my apologies for causing havoc! If there’s anything else that’s busted, lemme know.

**Comment by lemeurherve** [comment]
I'm wondering if I shouldn't have forked your repo instead of creating a new one. WDYT?

**Comment by halkeye** [comment]
https://ci.jenkins.io/job/Infra/job/plugin-site-api/job/master/342/console success \o/

**Comment by abayer** [comment]
I had that thought myself too late, but dealt with it by renaming my original repo and forking this under my user. =)

**Pull request merged**
